{% set name = "sphinxtesters" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0ba0a366436165ec5920c736ed757b49ff29dbd3e4133eeb09d7aaede0867860 

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - docutils
    - sphinx

test:
  imports:
    - sphinxtesters
    - sphinxtesters.tests

about:
  home: http://github.com/matthew-brett/sphinxtesters
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Utilities for testing Sphinx extensions
  
  description: |
    Utilities for testing Sphinx extensions
  doc_url: http://github.com/matthew-brett/sphinxtesters
  dev_url: http://github.com/matthew-brett/sphinxtesters

extra:
  recipe-maintainers:
    - CurtLH 
