{% set name = "sphinxtesters" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 09c456e1cd61ec99b64851e2990d2152fdf05bb53d87f3b294f22d73f939d6ca

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - docutils
    - sphinx

test:
  imports:
    - sphinxtesters
    - sphinxtesters.tests

about:
  home: http://github.com/matthew-brett/sphinxtesters
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Utilities for testing Sphinx extensions

  description: |
    Utilities for testing Sphinx extensions
  doc_url: http://github.com/matthew-brett/sphinxtesters
  dev_url: http://github.com/matthew-brett/sphinxtesters

extra:
  recipe-maintainers:
    - CurtLH
