travis:
  secure:
    BINSTAR_TOKEN: biHnXMTmzcbKJjo7XUbEP6NPDyZ8S1eWvb9UrSyiyWH8k4KPS2CEh6erN0DsSPkcUitcIQkgDKYNmyuc8FPnu+LOiUTi4fHX7pU11isVGJ1owFAlt2qZlYnf1+4CpnROoUimug9w9Qu3iBBn2pHOewgjhlv2UPpoPyVd6jsu8XSiYrWp5sunMT81oEms/43pEeTPgehPoQxWxpsWFd3DfvHbHfDu8xmfMdzg4ZgsalSn40f1FW5XAOniKD2joUSRIb513cMeLhyDo5QxoV4JF8fyg4MQhkQvYbmShQwNOupgZaJkoiQ0ha2H7IyVKWgQ/Vd9dE4+zQ04JyJmdRF3VtDTf0RoVRzjj949HoUJGO20m+T5eQPFCUaicdHnhVSZs3A0niGuwpSUtZi020ghuT33NWRl/rVIL2wAh0ToV+GVGov4U0eNypztlQ4rNILUw2cDPwME3EW9jElgOj5uB2u/fdVo+FLNGoC7ktd56ASXVDLyYmbXjBOy7+U/nOsr07wYNHKOnJyBvGTyly3YuqX0zMvtZ0lsnw6zHvCcTfUerPW7OxK402qy7SMkuUZaI0tL/L4YeeNcMSIDsvP+ANXw4IQI2AryyKJzFEYQGH+Dv5x9o0VmYrdocoGz9cHPVQfUZB5CmRDFr0xKaVddl/pQ188S2EfuLMhTp2wyhZI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
