travis:
  secure:
    BINSTAR_TOKEN: Zc1tt90xcF+Nz7hymIDR/3KIbzZzICFhSiQONS1YD2HwbwR/ZCbG7u/B6dDy90HWEOiEwuAibO1rf9GKwe7sSwKZ2kfaO7KOmA/7EPJw31t3mtwlPKXEFG/vUT49eZRSXAE1kJe/JbR7dcARu1LltHu+FRGTGth0fhlrGgtMbwNpeXKMRPA8kZOFYi33zvhsgvwr9Fs4shS267yo+xZtq5L0XbayUo7z7kLrAjvXFr9hUHcoNKL04SQy9hNuOnWPRdSuaOVAA+g1tacMVlT/f4S4mvyhS2U0NUd2awTaB5j+iLTxrjIzhxkS/afjp6RCZtV0e1okyL5QtCuqMyz7NDRM0MnX2kstUfC0b6zc1a6eAKfymSBs0HT0TVGKc99Sg+TeqpXE6qOV+MPGUkGnCgZbZ10d1LLRFjEs5XM1fb2gvkk0otY1PnzKx3ygP46Efc/0atr2QSEXUqJ/w7ugf89EAYAxZ4ZdhLNb82vqPrqcDX1fgFQVrNOv8CkbEmKtDn1tXZHbRsh4KROqpaH81AIB0jLXc3XoVOARKWCaY5ScrxBJf/sAYIUEW8eVrxzF45bjHz//dwAXgLhX626tk8ePfDInZ25oyRqmzeDBEiavwdlkO7NCz4Fv6LcIFfkTUa2tVyV3lJ7pBAUeGeLHUy82xfpKBG3goKR/PBkALUk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
